export const ACTION = {
  INIT: 0,
  ADD_TRACK: 1,
  CLEAN_LOAD_TRACK: 2,
  DELETE_TRACK: 3,
  ADD_HT_TRACK: 4,
  DELETE_HT_TRACK: 5,
  ADD_FILE_TRACK: 6,
  DELETE_FILE_TRACK: 7,
  HIDE_HT_TRACK: 8,
  SHOW_HT_TRACK: 9,
};
